"use client";
import {BookOpen,Clock3,MapPin,UserRound} from "lucide-react";import {useMemo,useState} from "react";
const grades=["6º ano","7º ano","8º ano","9º ano","1º ano do Ensino Médio","2º ano do Ensino Médio","3º ano do Ensino Médio"];
const weekdays=["Segunda","Terça","Quarta","Quinta","Sexta"];
const times=[["07:00","07:50"],["07:50","08:40"],["08:40","09:30"],["09:50","10:40"],["10:40","11:30"],["11:30","12:20"]];
const fundamental=[
  ["Matemática","Ana Paula","Sala 12"],["Língua Portuguesa","Marina Costa","Sala 12"],["Ciências","Juliana Freitas","Lab. Ciências"],["História","João Santos","Sala 08"],["Geografia","Renata Campos","Sala 10"],["Inglês","Laura Dias","Sala 08"],["Educação Física","Paulo Reis","Quadra"],["Arte","Helena Martins","Sala de Arte"]
];
const medio=[
  ["Matemática","Ana Paula","Sala 12"],["Língua Portuguesa","Marina Costa","Sala 12"],["Biologia","Juliana Freitas","Lab. Ciências"],["Física","Rafael Gomes","Lab. Física"],["Química","Camila Rocha","Lab. Química"],["História","João Santos","Sala 08"],["Geografia","Renata Campos","Sala 10"],["Inglês","Laura Dias","Sala 08"],["Sociologia","Eduardo Ramos","Sala 14"],["Educação Física","Paulo Reis","Quadra"]
];
export function ScheduleExplorer(){const[selected,setSelected]=useState(grades[0]);const gradeIndex=grades.indexOf(selected);const subjects=gradeIndex<4?fundamental:medio;const timetable=useMemo(()=>weekdays.map((day,dayIndex)=>({day,items:times.map(([start,end],lessonIndex)=>{const subject=subjects[(lessonIndex*2+dayIndex+gradeIndex)%subjects.length];return{start,end,subject:subject[0],teacher:subject[1],room:subject[2]}})})),[gradeIndex,subjects]);const first=timetable[0].items[0];return <><div className="mb-6 grid gap-4 md:grid-cols-[1fr_300px]"><div className="card bg-gradient-to-r from-blue-600 to-violet-600 p-5 text-white"><p className="text-sm font-bold text-blue-100">PRIMEIRA AULA DE SEGUNDA-FEIRA</p><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">{first.subject}</h2><p className="text-blue-100">{first.start} às {first.end} · {first.room}</p></div><span className="rounded-xl bg-white/15 px-4 py-2 font-bold">{selected}</span></div></div><label className="card flex flex-col justify-center p-4 text-sm font-bold">Selecione a turma<select value={selected} onChange={event=>setSelected(event.target.value)} className="input mt-2" aria-label="Selecionar ano escolar">{grades.map(grade=><option key={grade}>{grade}</option>)}</select></label></div><div className="mb-4 flex items-center gap-2"><BookOpen className="text-blue-600"/><div><h2 className="font-black">Grade semanal — {selected}</h2><p className="muted text-xs">6 aulas por dia · Intervalo das 9h30 às 9h50</p></div></div><div className="grid gap-5 lg:grid-cols-5">{timetable.map(column=><section className="card p-4" key={column.day}><h2 className="border-b pb-3 text-lg font-black">{column.day}</h2><div className="mt-3 space-y-3">{column.items.map(item=><div className="rounded-xl border p-3 transition hover:border-blue-300 hover:bg-blue-50/40 dark:hover:bg-blue-950/30" key={item.start}><p className="flex items-center gap-1 text-xs font-bold text-blue-600"><Clock3 size={13}/>{item.start}–{item.end}</p><h3 className="mt-1 text-sm font-black">{item.subject}</h3><p className="muted mt-2 flex gap-1 text-xs"><UserRound size={13}/>{item.teacher}</p><p className="muted mt-1 flex gap-1 text-xs"><MapPin size={13}/>{item.room}</p></div>)}</div></section>)}</div></>}
