export const events = [
  {id:"feira-ciencias",title:"Feira de Ciências e Tecnologia",description:"Projetos inovadores desenvolvidos pelos alunos em uma tarde de descobertas.",date:"2026-08-18",time:"13:30",location:"Ginásio principal",category:"Acadêmico",image:"https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=900&q=80",spots:18,status:"Disponível"},
  {id:"interclasses",title:"Jogos Interclasses",description:"Uma semana de esporte, integração e espírito de equipe.",date:"2026-08-25",time:"08:00",location:"Complexo esportivo",category:"Esporte",image:"https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=900&q=80",spots:0,status:"Lotado"},
  {id:"mostra-cultural",title:"Mostra Cultural",description:"Arte, música e cultura produzidas por toda a comunidade escolar.",date:"2026-09-04",time:"18:30",location:"Auditório",category:"Cultura",image:"https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=900&q=80",spots:42,status:"Disponível"},
  {id:"hackathon-escolar",title:"Hackathon Sanico Teles",description:"Uma maratona de programação para criar soluções que melhorem a vida escolar.",date:"2026-09-12",time:"08:00",location:"Laboratórios de informática",category:"Tecnologia",image:"https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=900&q=80",spots:24,status:"Disponível"},
  {id:"festival-talentos",title:"Festival de Talentos",description:"Música, dança, poesia e apresentações dos talentos da nossa escola.",date:"2026-09-19",time:"17:30",location:"Quadra coberta",category:"Cultura",image:"https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=900&q=80",spots:65,status:"Disponível"},
  {id:"palestra-carreiras",title:"Conexão com o Futuro",description:"Profissionais de diferentes áreas compartilham experiências e caminhos de carreira.",date:"2026-09-24",time:"10:00",location:"Auditório",category:"Acadêmico",image:"https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=900&q=80",spots:36,status:"Disponível"},
  {id:"torneio-xadrez",title:"Torneio Escolar de Xadrez",description:"Competição aberta para estudantes iniciantes e experientes.",date:"2026-10-03",time:"09:00",location:"Biblioteca",category:"Esporte",image:"https://images.unsplash.com/photo-1586165368502-1bad197a6461?auto=format&fit=crop&w=900&q=80",spots:12,status:"Disponível"},
  {id:"semana-meio-ambiente",title:"Semana do Meio Ambiente",description:"Oficinas, exposições e ações práticas para uma escola mais sustentável.",date:"2026-10-13",time:"08:30",location:"Pátio central",category:"Comunidade",image:"https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=900&q=80",spots:80,status:"Disponível"},
  {id:"visita-universidade",title:"Visita Técnica à Universidade",description:"Conheça laboratórios, cursos e projetos de pesquisa em uma visita orientada.",date:"2026-10-21",time:"07:00",location:"Saída pelo portão principal",category:"Acadêmico",image:"https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=900&q=80",spots:0,status:"Lotado"},
  {id:"gincana-solidaria",title:"Gincana Solidária",description:"Equipes, desafios e arrecadação de alimentos em benefício da comunidade.",date:"2026-11-07",time:"08:00",location:"Complexo esportivo",category:"Comunidade",image:"https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=900&q=80",spots:54,status:"Disponível"},
  {id:"formatura-tecnicos",title:"Cerimônia de Formatura",description:"Celebração de encerramento para as turmas concluintes dos cursos técnicos.",date:"2026-12-12",time:"19:00",location:"Auditório municipal",category:"Institucional",image:"https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=900&q=80",spots:0,status:"Encerrado"},
];
export const clubs = [
  {id:"robotica",name:"Clube de Robótica",description:"Crie robôs, aprenda automação e participe de competições.",leader:"Prof. Ricardo Alves",meeting:"Quartas, 14h",members:24,category:"Tecnologia",color:"from-blue-500 to-cyan-400"},
  {id:"leitura",name:"Círculo de Leitura",description:"Conversas, descobertas e novas perspectivas através dos livros.",leader:"Profa. Marina Costa",meeting:"Sextas, 12h30",members:18,category:"Cultura",color:"from-violet-500 to-fuchsia-400"},
  {id:"xadrez",name:"Clube de Xadrez",description:"Estratégia, raciocínio e torneios para todos os níveis.",leader:"Prof. André Lima",meeting:"Terças, 15h",members:31,category:"Esporte",color:"from-amber-500 to-orange-400"},
  {id:"programacao",name:"Clube de Programação",description:"Desenvolva sites, aplicativos e jogos enquanto aprende lógica na prática.",leader:"Prof. Carlos Melo",meeting:"Quintas, 14h",members:27,category:"Tecnologia",color:"from-cyan-500 to-blue-600"},
  {id:"teatro",name:"Grupo de Teatro",description:"Expressão corporal, interpretação e produções para o palco da escola.",leader:"Profa. Helena Martins",meeting:"Segundas, 16h",members:22,category:"Cultura",color:"from-fuchsia-500 to-rose-500"},
  {id:"musica",name:"Clube de Música",description:"Encontros para instrumentistas, cantores e estudantes apaixonados por música.",leader:"Prof. Marcelo Nunes",meeting:"Sextas, 14h30",members:35,category:"Cultura",color:"from-purple-500 to-indigo-500"},
  {id:"fotografia",name:"Clube de Fotografia",description:"Aprenda composição, iluminação e edição registrando o cotidiano escolar.",leader:"Profa. Camila Rocha",meeting:"Quartas, 15h30",members:19,category:"Arte",color:"from-slate-600 to-blue-500"},
  {id:"ciencias",name:"Jovens Cientistas",description:"Experimentos, pesquisa e preparação para feiras e olimpíadas científicas.",leader:"Profa. Juliana Freitas",meeting:"Terças, 14h",members:26,category:"Acadêmico",color:"from-emerald-500 to-teal-500"},
  {id:"futsal",name:"Equipe de Futsal",description:"Treinos técnicos, trabalho em equipe e preparação para campeonatos escolares.",leader:"Prof. Paulo Reis",meeting:"Segundas e quintas, 17h",members:20,category:"Esporte",color:"from-orange-500 to-red-500"},
  {id:"meio-ambiente",name:"Coletivo Escola Verde",description:"Ações sustentáveis, horta escolar e projetos de educação ambiental.",leader:"Profa. Renata Campos",meeting:"Sextas, 13h30",members:29,category:"Comunidade",color:"from-green-500 to-emerald-600"},
  {id:"empreendedorismo",name:"Clube de Empreendedorismo",description:"Transforme ideias em projetos com criatividade, planejamento e colaboração.",leader:"Prof. Eduardo Ramos",meeting:"Quartas, 13h30",members:23,category:"Acadêmico",color:"from-yellow-500 to-amber-600"},
];
export const news = [
  {id:"olimpiada",title:"Alunos conquistam medalhas na Olimpíada de Matemática",summary:"Nossa equipe alcançou resultados históricos na etapa estadual.",category:"Conquistas",author:"Comunicação Escolar",date:"2026-07-10",featured:true,image:"https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1000&q=80"},
  {id:"laboratorio",title:"Novo laboratório maker é inaugurado",summary:"O espaço amplia as possibilidades para projetos práticos e inovação.",category:"Institucional",author:"Direção",date:"2026-07-05",featured:false,image:"https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&w=1000&q=80"},
  {id:"ferias",title:"Programação especial para as férias",summary:"Confira oficinas e atividades abertas à comunidade durante julho.",category:"Comunicados",author:"Coordenação",date:"2026-06-29",featured:false,image:"https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1000&q=80"},
];
export const schedule = [
 {day:"Segunda",items:[["07:30","Matemática","Ana Paula","Sala 12"],["09:20","Programação Web","Ricardo Alves","Lab 03"],["11:10","Português","Marina Costa","Sala 12"]]},
 {day:"Terça",items:[["07:30","Banco de Dados","Carlos Melo","Lab 02"],["09:20","História","João Santos","Sala 12"],["11:10","Redes","André Lima","Lab 01"]]},
 {day:"Quarta",items:[["07:30","Programação Web","Ricardo Alves","Lab 03"],["09:20","Inglês","Laura Dias","Sala 08"],["11:10","Matemática","Ana Paula","Sala 12"]]},
 {day:"Quinta",items:[["07:30","Redes","André Lima","Lab 01"],["09:20","Banco de Dados","Carlos Melo","Lab 02"],["11:10","Projeto Integrador","Ricardo Alves","Lab 03"]]},
 {day:"Sexta",items:[["07:30","Português","Marina Costa","Sala 12"],["09:20","Projeto Integrador","Ricardo Alves","Lab 03"],["11:10","Educação Física","Paulo Reis","Quadra"]]},
];
export const calendarEntries = [
 {date:"2026-07-15",title:"Entrega do projeto de Banco de Dados",type:"Trabalho"},{date:"2026-07-18",title:"Reunião de representantes",type:"Reunião"},{date:"2026-07-22",title:"Avaliação de Matemática",type:"Prova"},{date:"2026-07-28",title:"Oficina de carreiras",type:"Atividade"},{date:"2026-08-18",title:"Feira de Ciências",type:"Evento"}
];
export const menu = [
 {day:"Segunda",breakfast:"Pão de queijo e vitamina de banana",lunch:"Arroz, feijão, frango grelhado e salada",lunchLate:"Arroz, feijão, carne ensopada com batatas e legumes",snack:"Bolo de cenoura e leite"},
 {day:"Terça",breakfast:"Cuscuz com ovo e suco",lunch:"Macarrão à bolonhesa e legumes",lunchLate:"Arroz, feijão, filé de frango ao molho e salada",snack:"Frutas da estação"},
 {day:"Quarta",breakfast:"Pão integral com queijo e leite",lunch:"Arroz, feijão, carne cozida e salada",lunchLate:"Arroz, feijão, omelete de forno e legumes refogados",snack:"Iogurte com granola"},
 {day:"Quinta",breakfast:"Tapioca com queijo e suco",lunch:"Escondidinho de frango e salada",lunchLate:"Arroz, feijão, almôndegas ao molho e cenoura cozida",snack:"Biscoito integral e vitamina"},
 {day:"Sexta",breakfast:"Cereal, frutas e leite",lunch:"Arroz, feijão, peixe assado e legumes",lunchLate:"Arroz, feijão, frango xadrez e salada verde",snack:"Sanduíche natural"}
];
